services:
  snake:
    image: ubermetroid/snake:latest
    container_name: snake
    restart: unless-stopped
    ports:
      - ${PORT:-4501}:4501
    volumes:
      - ${SNAKE_DATA_PATH:-./data}:/app/data
    environment:
      PORT: 4501
      SITE_TITLE: ${SNAKE_SITE_TITLE:-Snake}
      SNAKE_PIN: ${SNAKE_PIN:-}
      BASE_URL: ${SNAKE_BASE_URL:-http://localhost:4501}
      ALLOWED_ORIGINS: ${SNAKE_ALLOWED_ORIGINS:-*}
      TZ: ${TZ:-UTC}
      ENABLE_TRANSLATION: ${ENABLE_TRANSLATION:-false}
      ENABLE_THEMES: ${ENABLE_THEMES:-true}
      ENABLE_PRINT: ${ENABLE_PRINT:-true}
      MAX_ATTEMPTS: ${MAX_ATTEMPTS:-5}